# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from BD import *
from modules import *
import tkinter.messagebox as mb
import os
import secrets
import string
from allwidjets import *




class Ui_Form_utorization(object):


    def setupUi(self, Form_utorization):
        
        Form_utorization.setObjectName("Form_utorization")
        Form_utorization.setEnabled(True)
        Form_utorization.resize(691, 574)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_utorization.sizePolicy().hasHeightForWidth())
        Form_utorization.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        Form_utorization.setFont(font)
        Form_utorization.setWindowTitle("Авторизация")
        Form_utorization.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(104, 155, 194, 255), stop:1 rgba(220, 165, 166, 255));")
        self.centralwidget = QtWidgets.QWidget(Form_utorization)
        self.centralwidget.setObjectName("centralwidget")
        self.log_in_button = QtWidgets.QPushButton("Войти",self.centralwidget)
        self.log_in_button.setGeometry(QtCore.QRect(360, 420, 301, 121))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.log_in_button.setFont(font)
        self.log_in_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_in_button.setStyleSheet("background-color: rgb(181, 206, 245);")
        self.log_in_button.setObjectName("log_in_button")
        self.forgot_password_button = QtWidgets.QPushButton("Забыл пароль", self.centralwidget)
        self.forgot_password_button.setGeometry(QtCore.QRect(30, 420, 301, 121))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.forgot_password_button.setFont(font)
        self.forgot_password_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_password_button.setStyleSheet("background-color: rgb(181, 206, 245);")
        self.forgot_password_button.setObjectName("forgot_password_button")
        self.login_password_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.login_password_groupBox.setGeometry(QtCore.QRect(0, 0, 691, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_password_groupBox.sizePolicy().hasHeightForWidth())
        self.login_password_groupBox.setSizePolicy(sizePolicy)
        self.login_password_groupBox.setAutoFillBackground(False)
        self.login_password_groupBox.setTitle("")
        self.login_password_groupBox.setObjectName("login_password_groupBox")
        self.login_label = QtWidgets.QLabel("Логин", self.login_password_groupBox)
        self.login_label.setGeometry(QtCore.QRect(30, 30, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.login_label.setFont(font)
        self.login_label.setAutoFillBackground(False)
        self.login_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(108, 155, 193, 255), stop:1 rgba(128, 157, 188, 255));")
        self.login_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_label.setObjectName("login_label")
        self.login_input = QtWidgets.QLineEdit(self.login_password_groupBox)
        self.login_input.setGeometry(QtCore.QRect(30, 110, 631, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.login_input.setFont(font)
        self.login_input.setStyleSheet("background-color: rgb(181, 206, 245);")
        self.login_input.setFrame(True)
        self.login_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.login_input.setObjectName("login_input")
        self.password_label = QtWidgets.QLabel("Пароль", self.login_password_groupBox)
        self.password_label.setGeometry(QtCore.QRect(30, 190, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.password_label.setFont(font)
        self.password_label.setAutoFillBackground(False)
        self.password_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 157, 189, 255), stop:1 rgba(145, 159, 184, 255));")
        self.password_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password_label.setObjectName("password_label")
        self.password_input = QtWidgets.QLineEdit(self.login_password_groupBox)
        self.password_input.setGeometry(QtCore.QRect(30, 270, 631, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color: rgb(181, 206, 245);")
        self.password_input.setInputMask("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_input.setClearButtonEnabled(False)
        self.password_input.setObjectName("password_input")
        self.login_password_groupBox.raise_()
        self.log_in_button.raise_()
        self.forgot_password_button.raise_()



        self.set_buttons_click()

    # Первый вход, создание пользователя и ролей 
        first_login = First_login()
        module_autorization = Autorization()


        if first_login.is_first_login():
            first_login.first_login("Администратор", "Администратор", "Администратор","ychet.po@gmail.com","admin","admin")
            mb.showinfo("Информация", "Пользователь добавлен, вы можете зайти под данными: Логин - admin Пароль - admin")



    def set_buttons_click(self):
        self.log_in_button.clicked.connect(self.log_in_system)
        self.forgot_password_button.clicked.connect(self.forgot_password)

        # self.log_in_button.clicked.connect(lambda: self.log_in_system(log_in_button.text()))

    def log_in_system(self):

        login = self.login_input.text()
        passwd = self.password_input.text()
        module_autorization = Autorization()


        # mb.showerror("Ошибка", login)
        if not module_autorization.check_login(login):
            mb.showerror("Ошибка", "Такого логина нет")
            return
        if not (module_autorization.get_password() == passwd):
            mb.showerror("Ошибка", "Неправильный пароль")
            return

        


        global Form_utorization, Form_main, my_login
                
        my_login = login

        Form_utorization.hide()

        get_data = Bd_get_data()
        role = get_data.get_role(login)
        dostup = get_data.get_dostup(login)
        
        ui_main.set_name(login, role, dostup)
        Form_main.show()

        
    def forgot_password(self):

        alphabet = string.ascii_letters + string.digits
        password = ''.join(secrets.choice(alphabet) for i in range(8))
        
        login = self.login_input.text()

        mail_pass = Send_email()
        get_data = Bd_get_data()

        edit_pass = Bd_edit()
        auth = Autorization()

        id_user = auth.get_id(login)


        crypt = Crypt()

        edit_pass.edit_polz_password(id_user, crypt.encrypt(password))

        # email = get_data.get_email(login)
        email = "silaenckov2014@yandex.ru"
        mail_pass.send("ychet.po", "swfi ciqc lani rhvm" , email, mail_pass.codPasseordHtml(password))

        mb.showinfo("Информация", "Вам на почту был выслан новый пароль")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)



    ui = Ui_Form_utorization()
    ui.setupUi(Form_utorization)
    Form_utorization.show()

    ui1 = Ui_MainWindow()
    ui1.setupUi(Form)
    sys.exit(app.exec_())